name: Build and Release Executable

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest

    # GitHub Actions'a Release oluşturması için izin veriyoruz:
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Build and Publish Electron App
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx electron-builder --win --publish always